export const ADD_TO_CART = 'CART/ADD_TO_CART'
export const GET_CART_PRODUCTS = 'CART/GET_CART_PRODUCTS'
export const SET_CART_PRODUCTS = 'CART/SET_CART_PRODUCTS'
export const REMOVE_PRODUCT_FROM_CART = 'CART/REMOVE_PRODUCT_FROM_CART'
export const CLEAR_CART = 'CART/CLEAR_CART'


export const ADD_TO_CART_ERROR = 'CART/ADD_TO_CART_ERROR'
export const GET_CART_PRODUCTS_ERROR = 'CART/GET_CART_PRODUCTS_ERROR'
export const CLEAR_CART_ERROR = 'CART/CLEAR_CART_ERROR'