export const SET_IS_LOGIN_WINDOW_OPEN = 'APP/SET_IS_LOGIN_WINDOW_OPEN'
export const SET_IS_REGISTRATION_WINDOW_OPEN = 'APP/SET_IS_REGISTRATION_WINDOW_OPEN'
export const SET_IS_LOADING = 'APP/SET_IS_LOADING'